# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'react-native-apptentive-module' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for react-native-apptentive-module
  pod 'apptentive-ios', '~> 4.0'

end

post_install do |pi|
  pi.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      unless pi.podfile.defined_in_file.read().include? "\nuse_frameworks!\n"
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'NO_USE_FRAMEWORKS=1'
      end
    end
  end
end
